on: push

name: Bundler

jobs:
  bundler:
    name: bundler
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: bundle-dependabot
      uses: skarlso/dependabot-bundler-action@v0.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # must have commit access and creating PR rights
        repo: test
        owner: Skarlso
        botName: Skarlso
        targetBranch: master