on:
  workflow_dispatch: {}

name: Bundler

permissions: write-all


jobs:
  bundler:
    name: bundler
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Cache go-build and mod
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build/
          ~/go/pkg/mod/
        key: go-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-
    - name: Install Dependabot Bundler
      run: |
        go install github.com/Skarlso/dependabot-bundler@f0501190f790fdb86525ead95f3004b7a56cb90f
    - name: Run Dependabot Bundler
      run: |
        dependabot-bundler \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --repo test \
          --owner Skarlso \
          --bot-name Skarlso \
          --target-branch main \
          --labels bug,duplicate \
          --signing-public-key "${{ secrets.GPG_SIGN }}" \
          --signing-private-key "${{ secrets.GPG_SECRET_SIGN }}" \
          --signing-key-passphrase "${{ secrets.GPG_KEY_PASSPHRASE }}" \
          --signing-name dependabot-bundler \
          --signing-email 126970507+dependabot-bundler@users.noreply.github.com \
          --author-name dependabot-bundler \
          --author-email 126970507+dependabot-bundler@users.noreply.github.com
