on:
  workflow_dispatch: {}

name: Bundler

permissions: write-all


jobs:
  bundler:
    name: bundler
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Cache go-build and mod
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build/
          ~/go/pkg/mod/
        key: go-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-
    - name: Install Dependabot Bundler
      run: |
        go install github.com/Skarlso/dependabot-bundler@5f8d42553e5b5f68d257e4eaed1f9a1715e93b25
    - name: Run Dependabot Bundler
      run: |
        dependabot-bundler \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --repo test \
          --owner Skarlso \
          --bot-name Skarlso \
          --target-branch main \
          --labels bug,duplicate \
          --signing-public-key ${{ secrets.GPG_SIGN }} \
          --signing-name "Github Action" \
          --signing-email "41898282+github-actions@users.noreply.github.com"
