on: push

jobs:
  bundler:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: bundle-dependabot
      uses: skarlso/dependabot-bundler-action
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # must have commit access and creating PR rights
        repo: ${{ github.event.repository.name }}
        owner: ${{ github.event.repository.owner }}
        botName: Skarlso
        targetBranch: master

