on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: watch for slash commands from users
        uses: skarlso/caretaker@v0.2.0
        with:
          command: slash
          owner: skarlso
          repo: test
          token: ${{ secrets.PROJECT_TOKEN }}
          pullRequestNumber: ${{ github.event.pull_request.number }}
          actor: ${{ github.actor }}
          commentBody: ${{ github.event.comment.body }}
          commentID: ${{ github.event.comment.node_id }} # used for applying reactions