name: Poller
on:
  workflow_dispatch:
    inputs:
      changeset:
        description: 'The id of the changeset to keep polling...'
        required: true
        default: ''

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.changeset }}!"
