on: push
name: Publish Action
jobs:
  push-action:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger the poller
      uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7
      with:
        workflow: Poller
        token: ${{ secrets.GITHUB_TOKEN }}
        inputs: '{ "changeset": "changeset-id" }'
