on: push
name: Publish Blog
jobs:
  blog-builder:
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack Notification
      uses: skarlso/slack-notification-action@main
      with:
        message: test message from action
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        channel: C011RS3S0UA
