on: push
name: Publish Action
jobs:
  push-action:
    runs-on: ubuntu-latest
    steps:
      # Create check run
      - uses: octokit/request-action@v2.x
        id: trigger_poller
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: Skarlso
          workflow_id: 14215184
          repo: test
          ref: ${{ github.ref }}
          inputs: | # The | is significant!
            |
            changeset: changeset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
