on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.
      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF#refs/*/})
      - name: Test
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
